### ISSUE TITLE
升级Xcode9后编译报错

### ISSUE THREAD

**Issue by ghost** [justXyS/FrameAniamtionImageView#1]
升级Xcode9后编译报错；
YCFrameAnimator.m line45
Implicit declaration of function 'select' is invalid in C99
Declaration of 'select' must be imported from module 'Darwin.POSIX.sys.time' before it is required

解决办法:
引入 #include <sys/time.h>

**Comment by CocoaKier** [comment]
我也遇到了这个问题

**Comment by CocoaKier** [comment]
已解决：
#include <sys/time.h>

**Comment by justXyS** [comment]
已经处理
